### ISSUE TITLE
Error: invalid numeric value to CoreGraphics API

### ISSUE THREAD

**Issue by doguhanokumus** [lminhtm/LMGaugeView#1]
LMGaugeView causes the following error on xcode 7 release ios9

```
<Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
```

**Comment by tbrookin** [comment]
I am getting the same message.  In my case, it occurs because I was setting numOfDivsions = 0
I don't want the division markers.  It looks like this causes a divide by zero error in the first few lines of drawRect:
