### ISSUE TITLE
Division/subdivision markers are misaligned

### ISSUE THREAD

**Issue by dulimarta** [lminhtm/LMGaugeView#2]
When the [min,max] range is not [0,100], the division/subdivision markers do not line up with the ring marker start/end. In the following screenshot my temperature range is [-50, 130].
Within the range [-50,130] the current value of 75 should be rendered at about 42% of the arc width (75/180 = 41.666666)

<img width="135" alt="gauge-subdiv" src="https://cloud.githubusercontent.com/assets/3125417/16171375/63f68798-353b-11e6-8b3c-e0025912fd5a.png">

**Comment by lminhtm** [comment]
@dulimarta Thank you for your bug report, I fixed it and created a release with version 1.0.2. Please check it again. 
// With your range [-50, 130], I think the value of 75 should be rendered at about (75 - (-50))/(130 - (-50)) = 69% of the arc width

**Comment by dulimarta** [comment]
Thank you for your prompt response.

Having the the min/max values displayed at the two ends of the arc will be a nice feature to have.

**Comment by lminhtm** [comment]
@dulimarta That's good idea, I will try it
