### ISSUE TITLE
Full cycle

### ISSUE THREAD

**Issue by jeffleeismyhero** [lminhtm/LMGaugeView#3]
How can the gauge start and end at the same point (e.g., top center like a watch)?

Setting `kDefaultStartAngle` to `M_PI_4 * 6` causes the start position to be the top center, but I cannot figure out what value to use for `kDefaultEndAngle`.

**Comment by lminhtm** [comment]
Hi @jeffleeismyhero,

#define kDefaultStartAngle                      M_PI_2 \* 3
#define kDefaultEndAngle                        M_PI_2 \* 3 + 2 \* M_PI

And change update this line:
self.divisionUnitAngle = self.numOfDivisions ? (M_PI \* 2 - ABS(self.endAngle - self.startAngle))/self.numOfDivisions : 0;
To:
self.divisionUnitAngle = self.numOfDivisions ? ABS(self.endAngle - self.startAngle)/self.numOfDivisions : 0;

Thank you,

**Comment by jeffleeismyhero** [comment]
Thanks for the help!
